### ISSUE TITLE
Chewing Gum Crash

### ISSUE THREAD

**Issue by SirUmnei** [AstroPenguin642/Replay-the-Spire#21]
First Run I did, got Chewing Gum. Crashed on Deck Shuffle.

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.actions.common.MakeTempCardInDrawPileAction.<init>(Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/cards/AbstractCard;IZZ)V
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.actions.common.MakeTempCardInDrawPileAction.<init>(Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/cards/AbstractCard;IZZ)V
	at com.megacrit.cardcrawl.relics.ChewingGum.onShuffle(ChewingGum.java:45)
	at com.megacrit.cardcrawl.actions.common.EmptyDeckShuffleAction.<init>(EmptyDeckShuffleAction.java:41)
	at com.megacrit.cardcrawl.actions.common.DrawCardAction.update(DrawCardAction.java:79)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:152)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:255)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2605)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:820)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:376)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by The-Evil-Pickle** [comment]
@SirUmnei  I'll take a look. Are you on the beta branch?

**Comment by SirUmnei** [comment]
Yes.

**Comment by The-Evil-Pickle** [comment]
Aight fixed these
