### ISSUE TITLE
Crash on entering campsite with Dead Branch

### ISSUE THREAD

**Issue by apantel** [AstroPenguin642/Replay-the-Spire#23]
`java.lang.NullPointerException: null
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.switchTexture(SpriteBatch.java:1056) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.draw(SpriteBatch.java:237) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.ui.campfire.AbstractCampfireOption.render(AbstractCampfireOption.java:67) ~[?:?]
	at com.megacrit.cardcrawl.rooms.CampfireUI.render(CampfireUI.java:314) ~[?:?]
	at com.megacrit.cardcrawl.rooms.RestRoom.render(RestRoom.java:77) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.render(AbstractDungeon.java:2758) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:395) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]`

Happens consistently since 6-21 patch.

**Comment by SirUmnei** [comment]
Having the same issue.
