### ISSUE TITLE
Crash on dark orbs with Raider's Mask

### ISSUE THREAD

**Issue by apantel** [AstroPenguin642/Replay-the-Spire#26]
I can't tell exactly what conditions trigger this, but I sometimes get crashes when dark orbs trigger when I have Raider's Mask.

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418) ~[?:1.8.0_144]
	at java.util.ArrayList.set(ArrayList.java:446) ~[?:1.8.0_144]
	at ReplayTheSpireMod.patches.ReplayDarkOrbPassivePatch.Postfix(ReplayDarkOrbPassivePatch.java:53) ~[ReplayTheSpireMod.jar:?]
	at com.megacrit.cardcrawl.orbs.Dark.onEndOfTurn(Dark.java:93) ~[?:?]
	at com.megacrit.cardcrawl.actions.defect.TimeBombAction.update(TimeBombAction.java:31) ~[ReplayTheSpireMod.jar:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:152) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:255) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2615) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:825) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:376) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
```

**Comment by The-Evil-Pickle** [comment]
I'll take a look at this as soon as I can; for now the relic has been temporarily removed.
