### ISSUE TITLE
Portal

### ISSUE THREAD

**Issue by Bospad** [AstroPenguin642/Replay-the-Spire#37]
I love the new events but the game crashes when you enter the portal (act1 in my case) and try to click Back after entering the portal.

**Comment by DanielWieder** [comment]
I just encountered this. Here is the exception in case it helps.

Exception: java.lang.NullPointerException
06:10:26.764 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:225) ~[?:?]
at com.megacrit.cardcrawl.rooms.EventRoom.update(EventRoom.java:51) ~[desktop-1.0.jar:?]
at com.megacrit.cardcrawl.mod.replay.rooms.TeleportRoom.update(TeleportRoom.java:63) ~[ReplayTheSpireMod.jar:?]
at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2528) ~[?:?]
at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:881) ~[?:?]
at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:460) [?:?]
at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:

**Comment by Sinistralis** [comment]
You can work around this by entering the next room immediately before doing anything else btw for anyone else who is running into this.

**Comment by SilentJ28** [comment]
There doesn't seem to be anyway to resume the save after I hit this by trying to redeem the portal quest while still in the portal room

Trying to resume just gave the following crash:

05:42:46.873 INFO dungeons.AbstractDungeon> Map generation time: 18ms
05:42:46.873 INFO dungeons.AbstractDungeon> [INFO] Elite nodes identified: 8
05:42:46.874 INFO dungeons.AbstractDungeon> [INFO] Emerald Key  placed in: [2,7]
Exception: java.lang.ArrayIndexOutOfBoundsException: -1
05:42:46.878 ERROR core.CardCrawlGame> Exception caught
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418) ~[?:1.8.0_144]
	at java.util.ArrayList.get(ArrayList.java:431) ~[?:1.8.0_144]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.populatePathTaken(AbstractDungeon.java:510) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.Exordium.<init>(Exordium.java:110) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.getDungeon(CardCrawlGame.java:1400) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:866) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:434) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by Goblez** [comment]
Resuming the game after a crash with the portal (i also opened the quest log right after entering it).

19:30:44.574 INFO dungeons.AbstractDungeon> Game Seed: -4112287105325150858
19:30:44.575 INFO infinitespire.InfiniteSpire> adding initial quests
19:30:44.575 INFO dungeons.AbstractDungeon> Map generation time: 13ms
19:30:44.577 INFO dungeons.AbstractDungeon> Loading into: 6,9
com.megacrit.cardcrawl.mod.replay.rooms.TeleportRoom
com.megacrit.cardcrawl.rooms.EmptyRoom
19:30:44.579 INFO dungeons.AbstractDungeon> UNSPECIFIED CASE: NONE
Exception: java.lang.NullPointerException
19:30:44.580 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.mod.replay.relics.CounterBalance.onEnterRoom(CounterBalance.java:23) ~[ReplayTheSpireMod.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2229) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.populatePathTaken(AbstractDungeon.java:549) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.TheBeyond.<init>(TheBeyond.java:76) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.getDungeon(CardCrawlGame.java:1404) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:866) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:434) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by Frumgor** [comment]
This type of error also seems to occasionally occur when saving and resuming the game at any point during an act in which you took a portal room.
