### ISSUE TITLE
Capt. Abe crash loading music

### ISSUE THREAD

**Issue by Nolenz** [AstroPenguin642/Replay-the-Spire#63]
Recreated with both The Silent and Disciple (other modded character). Recreated on two separate PCs, both Windows 10. Game crashes as soon as you enter the boss room. Checked to make sure I had the latest version of everything (MTS, Basemod, and Replay)

```21:16:50.097 INFO dungeons.AbstractDungeon> Loading into: -1,15
21:16:50.099 INFO dungeons.AbstractDungeon> UNSPECIFIED CASE: NONE
21:16:50.102 INFO dungeons.AbstractDungeon> WALKING INTO BOSS ROOM
21:16:50.103 INFO helpers.MonsterHelper> Unspecified key: Pondfish in MonsterHelper.
21:16:50.155 INFO replayTheSpire.ReplayTheSpireMod> init Abe
21:16:50.203 INFO replayTheSpire.ReplayTheSpireMod> init Fish
21:16:50.204 INFO rooms.MonsterRoomBoss> BOSSES: 4
21:16:50.208 INFO audio.MusicMaster> Playing PIRATE_JOKE
21:16:50.210 INFO audio.TempMusic> ERROR: NO SUCH TEMP BGM: PIRATE_JOKE
21:16:50.212 ERROR core.CardCrawlGame> Exception caught
com.badlogic.gdx.utils.GdxRuntimeException: Unknown file extension for music: audio/music/PIRATE_JOKE
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.newMusic(OpenALAudio.java:126) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.newMusic(OpenALAudio.java:41) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.audio.MainMusic.newMusic(MainMusic.java:105) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.audio.TempMusic.getSong(TempMusic.java:84) ~[?:?]
	at com.megacrit.cardcrawl.audio.TempMusic.<init>(TempMusic.java:49) ~[?:?]
	at com.megacrit.cardcrawl.audio.TempMusic.<init>(TempMusic.java:39) ~[?:?]
	at com.megacrit.cardcrawl.audio.MusicMaster.playTempBgmInstantly(MusicMaster.java:108) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.playBgmInstantly(AbstractRoom.java:147) ~[?:?]
	at com.megacrit.cardcrawl.monsters.replay.PondfishBoss.usePreBattleAction(PondfishBoss.java:128) ~[ReplayTheSpireMod.jar:?]
	at com.megacrit.cardcrawl.monsters.MonsterGroup.usePreBattleAction(MonsterGroup.java:89) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.preBattlePrep(AbstractPlayer.java:1725) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2493) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.populatePathTaken(AbstractDungeon.java:565) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.TheCity.<init>(TheCity.java:89) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.getDungeon(CardCrawlGame.java:1385) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:877) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:466) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]```

**Comment by smonheim** [comment]
Seconded:
 
` 21:29:29.313 INFO dungeons.AbstractDungeon> UNSPECIFIED CASE: NONE
21:29:29.314 INFO dungeons.AbstractDungeon> WALKING INTO BOSS ROOM
21:29:29.315 INFO helpers.MonsterHelper> Unspecified key: Pondfish in MonsterHelper.
21:29:29.330 INFO replayTheSpire.ReplayTheSpireMod> init Abe
21:29:29.356 INFO replayTheSpire.ReplayTheSpireMod> init Fish
21:29:29.356 INFO rooms.MonsterRoomBoss> BOSSES: 2
21:29:29.358 INFO audio.MusicMaster> Playing PIRATE_JOKE
21:29:29.359 INFO audio.TempMusic> ERROR: NO SUCH TEMP BGM: PIRATE_JOKE
Exception: com.badlogic.gdx.utils.GdxRuntimeException: Unknown file extension for music: audio/music/PIRATE_JOKE
21:29:29.360 ERROR core.CardCrawlGame> Exception caught
com.badlogic.gdx.utils.GdxRuntimeException: Unknown file extension for music: audio/music/PIRATE_JOKE
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.newMusic(OpenALAudio.java:126) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.newMusic(OpenALAudio.java:41) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.audio.MainMusic.newMusic(MainMusic.java:105) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.audio.TempMusic.getSong(TempMusic.java:84) ~[?:?]
	at com.megacrit.cardcrawl.audio.TempMusic.<init>(TempMusic.java:49) ~[?:?]
	at com.megacrit.cardcrawl.audio.TempMusic.<init>(TempMusic.java:39) ~[?:?]
	at com.megacrit.cardcrawl.audio.MusicMaster.playTempBgmInstantly(MusicMaster.java:108) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.playBgmInstantly(AbstractRoom.java:147) ~[?:?]
	at com.megacrit.cardcrawl.monsters.replay.PondfishBoss.usePreBattleAction(PondfishBoss.java:128) ~[ReplayTheSpireMod.jar:?]
	at com.megacrit.cardcrawl.monsters.MonsterGroup.usePreBattleAction(MonsterGroup.java:89) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.preBattlePrep(AbstractPlayer.java:1725) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2493) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.populatePathTaken(AbstractDungeon.java:565) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.TheCity.<init>(TheCity.java:89) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.getDungeon(CardCrawlGame.java:1385) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:877) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:466) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
`

**Comment by Dorante997** [comment]
Guess i have the same problem here
![52](https://user-images.githubusercontent.com/42847474/45002766-8beb8700-afda-11e8-9407-85a2d2478385.PNG)
