### ISSUE TITLE
Possible EmotionChip crash

### ISSUE THREAD

**Issue by mikeynap** [AstroPenguin642/Replay-the-Spire#69]
I'm not sure if this is Replay-the-spire specific, but it was the only mod loaded when the crash happened. I also saw in the log that y'all patch ApplyPowerAction.update, which is referenced in the trace.

I had just acquired an emotionchip relic, and went to fight the Giant head (I had the boss relic that caused map randomization as well). As soon as the fight started, while the relics were lighting up on the top bar the game crashed. Stack trace is shown below:

java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.vfx.combat.FlashPowerEffect.<init>(FlashPowerEffect.java:29) ~[SlayTheSpire.jar:?]
	at com.megacrit.cardcrawl.powers.AbstractPower.flash(AbstractPower.java:415) ~[SlayTheSpire.jar:?]
	at com.megacrit.cardcrawl.actions.common.ApplyPowerAction.update(ApplyPowerAction.java:282) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:152) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:227) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2674) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:893) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:466) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [SlayTheSpire.jar:?]

My cards and relics are shown below:
03:09:09.951 INFO core.CardCrawlGame> Strike_B, 1
03:09:09.953 INFO core.CardCrawlGame> Strike_B, 1
03:09:09.953 INFO core.CardCrawlGame> Defend_B, 1
03:09:09.954 INFO core.CardCrawlGame> Defend_B, 0
03:09:09.954 INFO core.CardCrawlGame> Defend_B, 0
03:09:09.954 INFO core.CardCrawlGame> Defend_B, 0
03:09:09.954 INFO core.CardCrawlGame> Zap, 1
03:09:09.954 INFO core.CardCrawlGame> Dualcast, 0
03:09:09.954 INFO core.CardCrawlGame> Gash, 0
03:09:09.955 INFO core.CardCrawlGame> Gash, 0
03:09:09.955 INFO core.CardCrawlGame> Gash, 0
03:09:09.955 INFO core.CardCrawlGame> Gash, 0
03:09:09.955 INFO core.CardCrawlGame> ReplayGash, 1
03:09:09.955 INFO core.CardCrawlGame> Sweeping Beam, 0
03:09:09.955 INFO core.CardCrawlGame> Electrodynamics, 0
03:09:09.956 INFO core.CardCrawlGame> Gash, 0
03:09:09.956 INFO core.CardCrawlGame> Echo Form, 0
03:09:09.956 INFO core.CardCrawlGame> Go for the Eyes, 0
03:09:09.956 INFO core.CardCrawlGame> Rebound, 0
03:09:09.956 INFO core.CardCrawlGame> Hologram, 1
03:09:09.956 INFO core.CardCrawlGame> Coolheaded, 1
03:09:09.956 INFO core.CardCrawlGame> Machine Learning, 0
03:09:09.956 INFO core.CardCrawlGame> Biased Cognition, 0
03:09:09.956 INFO core.CardCrawlGame> Gash, 0
03:09:09.956 INFO core.CardCrawlGame> Conserve Battery, 1
03:09:09.957 INFO core.CardCrawlGame> Fission, 1
03:09:09.957 INFO core.CardCrawlGame> AbeCurse, 0
03:09:09.957 INFO core.CardCrawlGame> Stack, 0
03:09:09.958 INFO core.CardCrawlGame> Reinforced Body, 1
03:09:09.958 INFO core.CardCrawlGame> Stack, 1
03:09:09.958 INFO core.CardCrawlGame> Streamline, 1
03:09:09.961 INFO unlock.UnlockTracker> Already seen: Cracked Core
03:09:09.962 INFO unlock.UnlockTracker> Already seen: Anchor
03:09:09.964 INFO unlock.UnlockTracker> Already seen: Orichalcum
03:09:09.972 INFO unlock.UnlockTracker> Already seen: Replay_Grab Bag
03:09:09.975 INFO unlock.UnlockTracker> Already seen: Painkiller Herb
03:09:09.979 INFO unlock.UnlockTracker> Already seen: Nuclear Battery
03:09:09.981 INFO unlock.UnlockTracker> Already seen: Red Mask
03:09:09.982 INFO unlock.UnlockTracker> Already seen: Art of War
03:09:09.984 INFO unlock.UnlockTracker> Already seen: ReplayTheSpireMod:Multitool
03:09:09.987 INFO unlock.UnlockTracker> Already seen: Potion Belt
03:09:09.988 INFO unlock.UnlockTracker> Already seen: Matryoshka
03:09:09.989 INFO unlock.UnlockTracker> Already seen: Abe's Treasure
03:09:09.992 INFO unlock.UnlockTracker> Already seen: Emotion Chip

Sorry if this is not related to your mod, just figured I'd post it either way

**Comment by mikeynap** [comment]
That makes sense.
I see you changed `this.img = ImageMaster.loadImage("images/powers/32/slow.png");` to fix the giant head issue -- what change do you think fixed the Louse bug? Just outta curiosity.
