### ISSUE TITLE
Crash (possibly involving Garlic)

### ISSUE THREAD

**Issue by SirUmnei** [AstroPenguin642/Replay-the-Spire#7]
Game crashed once I got into the Elite Goblin fight. I was the Defect, and had Garlic. I'm also running the "Beta Mode" mod. Had no problems past 6-7 runs (all with the Defect).

Here's what it returned at the ModTheSpire thingie.

22:40:32.122 INFO dungeons.AbstractDungeon> UNSPECIFIED CASE: NONE
22:40:33.999 INFO basemod.BaseMod> publish on post power apply
22:40:34.103 INFO basemod.BaseMod> powers modified
22:40:34.302 INFO basemod.BaseMod> publish on post power apply
22:40:34.304 INFO basemod.BaseMod> powers modified
Exception: java.lang.NullPointerException
22:40:34.497 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at ReplayTheSpireMod.patches.ReplayApplyPowerPatch.Prefix(ReplayApplyPowerPatch.java:20) ~[ReplayTheSpireMod.jar:?]
	at com.megacrit.cardcrawl.actions.common.ApplyPowerAction.update(ApplyPowerAction.java) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:142) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:220) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2563) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:777) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:370) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
22:40:34.809 INFO helpers.FileSaver> Save thread interrupted!
22:40:34.809 INFO helpers.FileSaver> Save thread will die now.
Game closed.

**Comment by pymba1991** [comment]
Experiencing the same issue as mentioned above. Every time I reach Goblin Elite fight game crashes. Please solve it, as this makes game unplayable.

**Comment by SirHaesslich** [comment]
22:00:14.386 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
at ReplayTheSpireMod.patches.ReplayApplyPowerPatch.Prefix(ReplayApplyPowerPatch.java:20) ~[ReplayTheSpireMod.jar:?]
at com.megacrit.cardcrawl.actions.common.ApplyPowerAction.update(ApplyPowerAction.java) ~[?:?]
at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:142) ~[?:?]
at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:220) ~[?:?]
at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2563) ~[?:?]
at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:777) ~[?:?]
at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:370) [?:?]
at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
22:00:15.349 INFO helpers.FileSaver> Save thread interrupted!
22:00:15.350 INFO helpers.FileSaver> Save thread will die now.

[sentry-pool-1-thread-1] WARN io.sentry.connection.AbstractConnection.lockdown - Initiated a temporary lockdown because of exception: An exception occurred while submitting the event to the Sentry server.
[sentry-pool-1-thread-1] ERROR io.sentry.connection.AsyncConnection - An exception occurred while sending the event to Sentry.
io.sentry.connection.ConnectionException: An exception occurred while submitting the event to the Sentry server.
at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:216)
at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:75)
at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:185)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: connect timed out
at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
at java.net.PlainSocketImpl.connect(Unknown Source)
at java.net.SocksSocketImpl.connect(Unknown Source)
at java.net.Socket.connect(Unknown Source)
at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
at sun.net.NetworkClient.doConnect(Unknown Source)
at sun.net.www.http.HttpClient.openServer(Unknown Source)
at sun.net.www.http.HttpClient.openServer(Unknown Source)
at sun.net.www.protocol.https.HttpsClient.(Unknown Source)
at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:168)
... 5 more


Same here, Gremlin Elite as well. @SirUmnei I suggest you rename the issue for better clarity
