### ISSUE TITLE
Crash on starting the game

### ISSUE THREAD

**Issue by Jedi515** [AstroPenguin642/Replay-the-Spire#83]
ModVersion Info:
```
 - Java version (1.8.0_191)
 - Slay the Spire (10-25-2018)
 - ModTheSpire (3.5.0)
```
Mod list:
```
 - basemod (5.1.0)
 - stslib (1.3.0)
 - infinitespire (0.5.0)
 - BlakkMod (1.9)
 - hubris (0.11.1)
 - ShopMod (1.0.1)
 - MysticMod (0.12.1)
 - STS_AlwaysWhale (0.0.1)
 - relicsorter (1.1.1)
 - constructmod (0.9.93)
 - ReplayTheSpireMod (1.2.2)
 - RNG (1)
 - SpikesRelics (0.02)
```

Console log:
```
Caused by: java.lang.NoClassDefFoundError: com/megacrit/cardcrawl/cards/status/Void
	at replayTheSpire.ReplayTheSpireMod.receiveEditCards(ReplayTheSpireMod.java:1007)
	at basemod.BaseMod.publishEditCards(BaseMod.java:2161)
	at basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.EditCardsPatch.Prefix(EditCardsPatch.java:11)
	at com.megacrit.cardcrawl.helpers.CardLibrary.initialize(CardLibrary.java)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:284)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.lang.ClassNotFoundException: com.megacrit.cardcrawl.cards.status.Void
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.findClass(MTSClassLoader.java:82)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.loadClass(MTSClassLoader.java:65)
	... 7 more12:32:04.669 INFO helpers.File> Successfully saved file=D:\Steam\SteamApps\common\SlayTheSpire\preferences\STSUnlocks
```

Unmodded game works just fine.

Small upd: just played unmodded, had a woke one final boss who threw that void into my draw pile, no crashes or anything, drew it just fine, dropped an energy just fine, exhausted it with medkit just fine. No crashes on unmodded.

**Comment by Reoisasa** [comment]
I can confirm that I am getting a similar crash running just BaseMod, STSLib, and ReplayTheSpire. My full modlist was crashing and the debug seemed to indicate ReplayTheSpire was the problem, so I tried running it barebones to see if it still crashed. 
`
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoClassDefFoundError: com/megacrit/cardcrawl/cards/status/Void
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoClassDefFoundError: com/megacrit/cardcrawl/cards/status/Void
	at replayTheSpire.ReplayTheSpireMod.receiveEditCards(ReplayTheSpireMod.java:1007)
	at basemod.BaseMod.publishEditCards(BaseMod.java:2161)
	at basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.EditCardsPatch.Prefix(EditCardsPatch.java:11)
	at com.megacrit.cardcrawl.helpers.CardLibrary.initialize(CardLibrary.java)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:284)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.lang.ClassNotFoundException: com.megacrit.cardcrawl.cards.status.Void
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.findClass(MTSClassLoader.java:82)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.loadClass(MTSClassLoader.java:65)
	... 7 more
`

**Comment by Reoisasa** [comment]
The Evil Pickle you are literally a miracle worker. Thank you so much for all you do.

**Comment by Goblez** [comment]
Hello!

I would like to comment that i too had this/similar issue with the mod (crash at startup with similar java exceptions).
However i went into steam, started up the game after it had updated from steam with no mods.
Then i closed down the game and tried to run with the mods and suddenly all my selected mods worked.

The strange thing is that it looked like the game had updated in steam earlier, but maybe staring it with no mods helped with something? Or maybe it just looked updated?

**Comment by Jedi515** [comment]
Thanks for the update! It does work properly now.
