### ISSUE TITLE
Game crash when entering ? due to MirrorMist event

### ISSUE THREAD

**Issue by SilentJ28** [AstroPenguin642/Replay-the-Spire#89]
19:05:01.259 INFO dungeons.AbstractDungeon> GENERATING ROOM: EVENT
19:05:01.260 INFO dungeons.AbstractDungeon> Removed event: Mirror Mist from pool.
19:05:01.260 INFO helpers.EventHelper> ---------------------------
ERROR: Unspecified key: Mirror Mist in EventHelper.
---------------------------
19:05:01.260 INFO basemod.BaseMod> Looking for custom events...
19:05:01.291 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\saves\THE_GATHERER.autosave
19:05:01.292 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.helpers.CardLibrary.getCopy(CardLibrary.java:837) ~[?:?]
	at com.megacrit.cardcrawl.mod.replay.events.thebottom.MirrorMist.<init>(MirrorMist.java:400) ~[ReplayTheSpireMod.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_144]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_144]
	at basemod.patches.com.megacrit.cardcrawl.dungeons.AbstractDungeon.InitializeEventListPatch$GetEvent.Postfix(InitializeEventListPatch.java:23) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.helpers.EventHelper.getEvent(EventHelper.java:384) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.getEvent(AbstractDungeon.java:2447) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.generateEvent(AbstractDungeon.java:2341) ~[?:?]
	at com.megacrit.cardcrawl.rooms.EventRoom.onPlayerEntry(EventRoom.java:24) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2261) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.updateFading(AbstractDungeon.java:2784) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2471) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:882) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:434) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]

**Comment by SilentJ28** [comment]
This was while playing as The Gatherer character mod. The autosave immediately crashes when loaded since it tries to resume the same event

**Comment by SilentJ28** [comment]
modlist 
![image](https://user-images.githubusercontent.com/40654703/48796737-63685480-ecce-11e8-975c-84e17b85a8c4.png)
save
[THE_GATHERER.zip](https://github.com/AstroPenguin642/Replay-the-Spire/files/2601200/THE_GATHERER.zip)

**Comment by lionpkqq** [comment]
Mr. Pickle, please take a look at this too: https://github.com/lionpkqq/StS-BlackRuseMod/issues/28

**Comment by iUkka** [comment]
09:46:44.639 INFO helpers.AsyncSaver> Enqueue: qsize=0 file=preferences\STSDataTheSilent
09:46:44.640 INFO helpers.FileSaver> Dequeue: qsize=0 file=preferences\STSDataTheSilent
09:46:44.640 INFO saveAndContinue.SaveFile> Next Room: com.megacrit.cardcrawl.rooms.EventRoom
09:46:44.640 INFO helpers.File> Attempting to save file=c:\Games\SlayTheSpire\preferences\STSDataTheSilent
09:46:44.640 INFO replayTheSpire.ReplayTheSpireMod> Saving Data
09:46:44.672 INFO HubrisMod> Saving Data
09:46:44.672 INFO helpers.File> Successfully saved file=c:\Games\SlayTheSpire\preferences\STSDataTheSilent
09:46:44.677 INFO helpers.AsyncSaver> Enqueue: qsize=0 file=saves\THE_SILENT.autosave
09:46:44.677 INFO helpers.FileSaver> Dequeue: qsize=0 file=saves\THE_SILENT.autosave
09:46:44.677 INFO helpers.EventHelper> Rolling for room type... EVENT_RNG_COUNTER: 3
09:46:44.677 INFO helpers.File> Attempting to save file=c:\Games\SlayTheSpire\saves\THE_SILENT.autosave
09:46:44.678 INFO helpers.EventHelper> ROLL: 0.83369386
09:46:44.678 INFO helpers.EventHelper> ELIT: 0.2
09:46:44.679 INFO helpers.EventHelper> MNST: 0.1
09:46:44.679 INFO helpers.EventHelper> SHOP: 0.089999996
09:46:44.679 INFO helpers.EventHelper> TRSR: 0.06
09:46:44.680 INFO dungeons.AbstractDungeon> GENERATING ROOM: EVENT
09:46:44.681 INFO dungeons.AbstractDungeon> Removed event: Mirror Mist from pool.
09:46:44.682 INFO helpers.EventHelper> ---------------------------
ERROR: Unspecified key: Mirror Mist in EventHelper.
---------------------------
09:46:44.683 INFO basemod.BaseMod> Looking for custom events...
09:46:44.685 INFO helpers.File> Successfully saved file=c:\Games\SlayTheSpire\saves\THE_SILENT.autosave

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoClassDefFoundError: constructmod/cards/AbstractConstructCard
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoClassDefFoundError: constructmod/cards/AbstractConstructCard
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.findClass(MTSClassLoader.java:82)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.loadClass(MTSClassLoader.java:72)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at basemod.patches.com.megacrit.cardcrawl.dungeons.AbstractDungeon.InitializeEventListPatch$GetEvent.Postfix(InitializeEventListPatch.java:23)
	at com.megacrit.cardcrawl.helpers.EventHelper.getEvent(EventHelper.java:384)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.getEvent(AbstractDungeon.java:2447)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.generateEvent(AbstractDungeon.java:2341)
	at com.megacrit.cardcrawl.rooms.EventRoom.onPlayerEntry(EventRoom.java:24)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2261)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.updateFading(AbstractDungeon.java:2784)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2471)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:882)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:434)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.lang.ClassNotFoundException: constructmod.cards.AbstractConstructCard
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.findClass(MTSClassLoader.java:88)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.loadClass(MTSClassLoader.java:72)
	... 29 more
![image](https://user-images.githubusercontent.com/5823637/49504869-a2c8a080-f88b-11e8-804e-bd298db7e059.png)
