### ISSUE TITLE
Unable to launch mod

### ISSUE THREAD

**Issue by SirHaesslich** [AstroPenguin642/Replay-the-Spire#9]
At least second patch in a row I cannot play the RPtS mod, catching exception(below) even before starting to load the game.

javassist.NotFoundException: com.megacrit.cardcrawl.gashapon.NeowEvent
	at javassist.ClassPool.get(ClassPool.java:445)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:202)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:170)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:185)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$1(ModSelectWindow.java:189)
	at java.lang.Thread.run(Unknown Source)

**Comment by The-Evil-Pickle** [comment]
Fixed in the new version, download the latest jar from Releases.
